# Note about this file name.
# Convention is to use the type extension first and gql extension second.
# Types are query, subscription, mutation.
# You can also use the extension "graphql" instead of "gql".
query getChosenName($search: String) {
    chosenName(search: $search) {
        id
        image
        caption
        name
        regions
        states
        website
    }
}
